# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Install build dependencies for canvas
# RUN apk add --no-cache python3 make g++ cairo-dev pango-dev jpeg-dev giflib-dev

# Set working directory
WORKDIR /app

# Install dependencies
# COPY package.json package-lock.json ./
# RUN npm ci --omit=dev

# Copy source code
COPY . .

# Build TypeScript
RUN npm install 
RUN npm run build

# Default command uses stdio transport
CMD ["node", "dist/index.js"]
